/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2020-05-11 13:00:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class blog_002dsingle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\"><head>\r\n");
      out.write("    <title>Skillhunt - Free Bootstrap 4 Template by Colorlib</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&amp;display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/animate.css\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/owl.theme.default.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/aos.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/ionicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/jquery.timepicker.css\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/icomoon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/style.css\">\r\n");
      out.write("  <style type=\"text/css\">.scrollax-performance, .scrollax-performance *, .scrollax-performance *:before, .scrollax-performance *:after { pointer-events: none !important; -webkit-animation-play-state: paused !important; animation-play-state: paused !important; };</style><script type=\"text/javascript\" charset=\"UTF-8\" src=\"https://maps.googleapis.com/maps-api-v3/api/js/40/12/intl/ko_ALL/common.js\"></script><script type=\"text/javascript\" charset=\"UTF-8\" src=\"https://maps.googleapis.com/maps-api-v3/api/js/40/12/intl/ko_ALL/util.js\"></script><script type=\"text/javascript\" charset=\"UTF-8\" src=\"https://maps.googleapis.com/maps/api/js/AuthenticationService.Authenticate?1sfile%3A%2F%2F%2FC%3A%2FUsers%2FAdministrator%2FDesktop%2F%25ED%2582%25A4%25ED%258A%25B8%25EB%25A6%25AC%25ED%2594%2584%25EC%25A0%259D%25EB%2594%2594%25EC%259E%2590%25EC%259D%25B8%2Fskillhunt%2Fblog-single.html&amp;4sAIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;callback=_xdc_._f6x6u8&amp;key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;token=70302\"></script></head>\r\n");
      out.write("  <body data-aos-easing=\"slide\" data-aos-duration=\"800\" data-aos-delay=\"0\">\r\n");
      out.write("    \r\n");
      out.write("\t  <nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\" id=\"ftco-navbar\">\r\n");
      out.write("\t    <div class=\"container-fluid px-md-4\t\">\r\n");
      out.write("\t      <a class=\"navbar-brand\" href=\"index.html\">Skillhunt</a>\r\n");
      out.write("\t      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t        <span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("\t      </button>\r\n");
      out.write("\r\n");
      out.write("\t      <div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("\t        <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t          <li class=\"nav-item\"><a href=\"index.html\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("\t          <li class=\"nav-item\"><a href=\"browsejobs.html\" class=\"nav-link\">Browse Jobs</a></li>\r\n");
      out.write("\t          <li class=\"nav-item\"><a href=\"candidates.html\" class=\"nav-link\">Canditates</a></li>\r\n");
      out.write("\t          <li class=\"nav-item active\"><a href=\"blog.html\" class=\"nav-link\">Blog</a></li>\r\n");
      out.write("\t          <li class=\"nav-item\"><a href=\"contact.html\" class=\"nav-link\">Contact</a></li>\r\n");
      out.write("\t          <li class=\"nav-item cta mr-md-1\"><a href=\"new-post.html\" class=\"nav-link\">Post a Job</a></li>\r\n");
      out.write("\t          <li class=\"nav-item cta cta-colored\"><a href=\"job-post.html\" class=\"nav-link\">Want a Job</a></li>\r\n");
      out.write("\r\n");
      out.write("\t        </ul>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </nav>\r\n");
      out.write("    <!-- END nav -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"hero-wrap hero-wrap-2\" style=\"background-image: url(&quot;images/bg_1.jpg&quot;); background-position: 50% 0%;\" data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("      <div class=\"overlay\"></div>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row no-gutters slider-text align-items-end justify-content-start\">\r\n");
      out.write("          <div class=\"col-md-12 ftco-animate text-center mb-5 fadeInUp ftco-animated\">\r\n");
      out.write("          \t<p class=\"breadcrumbs mb-0\"><span class=\"mr-3\"><a href=\"index.html\">Home <i class=\"ion-ios-arrow-forward\"></i></a></span> <span class=\"mr-3\"><a href=\"blog.html\">Blog <i class=\"ion-ios-arrow-forward\"></i></a></span> <span>Blog Single</span></p>\r\n");
      out.write("            <h1 class=\"mb-3 bread\">Single Blog</h1>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t\t<section class=\"ftco-section ftco-degree-bg\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-8 ftco-animate fadeInUp ftco-animated\">\r\n");
      out.write("            <h2 class=\"mb-3\">It is a long established fact a reader be distracted</h2>\r\n");
      out.write("            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis, eius mollitia suscipit, quisquam doloremque distinctio perferendis et doloribus unde architecto optio laboriosam porro adipisci sapiente officiis nemo accusamus ad praesentium? Esse minima nisi et. Dolore perferendis, enim praesentium omnis, iste doloremque quia officia optio deserunt molestiae voluptates soluta architecto tempora.</p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <img src=\"images/image_7.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>Molestiae cupiditate inventore animi, maxime sapiente optio, illo est nemo veritatis repellat sunt doloribus nesciunt! Minima laborum magni reiciendis qui voluptate quisquam voluptatem soluta illo eum ullam incidunt rem assumenda eveniet eaque sequi deleniti tenetur dolore amet fugit perspiciatis ipsa, odit. Nesciunt dolor minima esse vero ut ea, repudiandae suscipit!</p>\r\n");
      out.write("            <h2 class=\"mb-3 mt-5\">#2. Creative WordPress Themes</h2>\r\n");
      out.write("            <p>Temporibus ad error suscipit exercitationem hic molestiae totam obcaecati rerum, eius aut, in. Exercitationem atque quidem tempora maiores ex architecto voluptatum aut officia doloremque. Error dolore voluptas, omnis molestias odio dignissimos culpa ex earum nisi consequatur quos odit quasi repellat qui officiis reiciendis incidunt hic non? Debitis commodi aut, adipisci.</p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <img src=\"images/image_8.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>Quisquam esse aliquam fuga distinctio, quidem delectus veritatis reiciendis. Nihil explicabo quod, est eos ipsum. Unde aut non tenetur tempore, nisi culpa voluptate maiores officiis quis vel ab consectetur suscipit veritatis nulla quos quia aspernatur perferendis, libero sint. Error, velit, porro. Deserunt minus, quibusdam iste enim veniam, modi rem maiores.</p>\r\n");
      out.write("            <p>Odit voluptatibus, eveniet vel nihil cum ullam dolores laborum, quo velit commodi rerum eum quidem pariatur! Quia fuga iste tenetur, ipsa vel nisi in dolorum consequatur, veritatis porro explicabo soluta commodi libero voluptatem similique id quidem? Blanditiis voluptates aperiam non magni. Reprehenderit nobis odit inventore, quia laboriosam harum excepturi ea.</p>\r\n");
      out.write("            <p>Adipisci vero culpa, eius nobis soluta. Dolore, maxime ullam ipsam quidem, dolor distinctio similique asperiores voluptas enim, exercitationem ratione aut adipisci modi quod quibusdam iusto, voluptates beatae iure nemo itaque laborum. Consequuntur et pariatur totam fuga eligendi vero dolorum provident. Voluptatibus, veritatis. Beatae numquam nam ab voluptatibus culpa, tenetur recusandae!</p>\r\n");
      out.write("            <p>Voluptas dolores dignissimos dolorum temporibus, autem aliquam ducimus at officia adipisci quasi nemo a perspiciatis provident magni laboriosam repudiandae iure iusto commodi debitis est blanditiis alias laborum sint dolore. Dolores, iure, reprehenderit. Error provident, pariatur cupiditate soluta doloremque aut ratione. Harum voluptates mollitia illo minus praesentium, rerum ipsa debitis, inventore?</p>\r\n");
      out.write("            <div class=\"tag-widget post-tag-container mb-5 mt-5\">\r\n");
      out.write("              <div class=\"tagcloud\">\r\n");
      out.write("                <a href=\"#\" class=\"tag-cloud-link\">Life</a>\r\n");
      out.write("                <a href=\"#\" class=\"tag-cloud-link\">Sport</a>\r\n");
      out.write("                <a href=\"#\" class=\"tag-cloud-link\">Tech</a>\r\n");
      out.write("                <a href=\"#\" class=\"tag-cloud-link\">Travel</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"about-author d-flex p-4 bg-light\">\r\n");
      out.write("              <div class=\"bio mr-5\">\r\n");
      out.write("                <img src=\"resources/images/person_1.jpg\" alt=\"Image placeholder\" class=\"img-fluid mb-4\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                <h3>George Washington</h3>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"pt-5 mt-5\">\r\n");
      out.write("              <h3 class=\"mb-5\">6 Comments</h3>\r\n");
      out.write("              <ul class=\"comment-list\">\r\n");
      out.write("                <li class=\"comment\">\r\n");
      out.write("                  <div class=\"vcard bio\">\r\n");
      out.write("                    <img src=\"images/person_1.jpg\" alt=\"Image placeholder\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"comment-body\">\r\n");
      out.write("                    <h3>John Doe</h3>\r\n");
      out.write("                    <div class=\"meta\">October 03, 2018 at 2:21pm</div>\r\n");
      out.write("                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>\r\n");
      out.write("                    <p><a href=\"#\" class=\"reply\">Reply</a></p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"comment\">\r\n");
      out.write("                  <div class=\"vcard bio\">\r\n");
      out.write("                    <img src=\"images/person_1.jpg\" alt=\"Image placeholder\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"comment-body\">\r\n");
      out.write("                    <h3>John Doe</h3>\r\n");
      out.write("                    <div class=\"meta\">October 03, 2018 at 2:21pm</div>\r\n");
      out.write("                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>\r\n");
      out.write("                    <p><a href=\"#\" class=\"reply\">Reply</a></p>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <ul class=\"children\">\r\n");
      out.write("                    <li class=\"comment\">\r\n");
      out.write("                      <div class=\"vcard bio\">\r\n");
      out.write("                        <img src=\"images/person_1.jpg\" alt=\"Image placeholder\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"comment-body\">\r\n");
      out.write("                        <h3>John Doe</h3>\r\n");
      out.write("                        <div class=\"meta\">October 03, 2018 at 2:21pm</div>\r\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>\r\n");
      out.write("                        <p><a href=\"#\" class=\"reply\">Reply</a></p>\r\n");
      out.write("                      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                      <ul class=\"children\">\r\n");
      out.write("                        <li class=\"comment\">\r\n");
      out.write("                          <div class=\"vcard bio\">\r\n");
      out.write("                            <img src=\"images/person_1.jpg\" alt=\"Image placeholder\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"comment-body\">\r\n");
      out.write("                            <h3>John Doe</h3>\r\n");
      out.write("                            <div class=\"meta\">October 03, 2018 at 2:21pm</div>\r\n");
      out.write("                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>\r\n");
      out.write("                            <p><a href=\"#\" class=\"reply\">Reply</a></p>\r\n");
      out.write("                          </div>\r\n");
      out.write("\r\n");
      out.write("                            <ul class=\"children\">\r\n");
      out.write("                              <li class=\"comment\">\r\n");
      out.write("                                <div class=\"vcard bio\">\r\n");
      out.write("                                  <img src=\"images/person_1.jpg\" alt=\"Image placeholder\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"comment-body\">\r\n");
      out.write("                                  <h3>John Doe</h3>\r\n");
      out.write("                                  <div class=\"meta\">October 03, 2018 at 2:21pm</div>\r\n");
      out.write("                                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>\r\n");
      out.write("                                  <p><a href=\"#\" class=\"reply\">Reply</a></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                              </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"comment\">\r\n");
      out.write("                  <div class=\"vcard bio\">\r\n");
      out.write("                    <img src=\"images/person_1.jpg\" alt=\"Image placeholder\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"comment-body\">\r\n");
      out.write("                    <h3>John Doe</h3>\r\n");
      out.write("                    <div class=\"meta\">October 03, 2018 at 2:21pm</div>\r\n");
      out.write("                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>\r\n");
      out.write("                    <p><a href=\"#\" class=\"reply\">Reply</a></p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("              <!-- END comment-list -->\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"comment-form-wrap pt-5\">\r\n");
      out.write("                <h3 class=\"mb-5\">Leave a comment</h3>\r\n");
      out.write("                <form action=\"#\" class=\"p-5 bg-light\">\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"name\">Name *</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"name\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"email\">Email *</label>\r\n");
      out.write("                    <input type=\"email\" class=\"form-control\" id=\"email\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"website\">Website</label>\r\n");
      out.write("                    <input type=\"url\" class=\"form-control\" id=\"website\">\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"message\">Message</label>\r\n");
      out.write("                    <textarea name=\"\" id=\"message\" cols=\"30\" rows=\"10\" class=\"form-control\"></textarea>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input type=\"submit\" value=\"Post Comment\" class=\"btn py-3 px-4 btn-primary\">\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                </form>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div> <!-- .col-md-8 -->\r\n");
      out.write("          <div class=\"col-md-4 pl-md-5 sidebar ftco-animate fadeInUp ftco-animated\">\r\n");
      out.write("            <div class=\"sidebar-box\">\r\n");
      out.write("              <form action=\"#\" class=\"search-form\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <span class=\"icon icon-search\"></span>\r\n");
      out.write("                  <input type=\"text\" class=\"form-control\" placeholder=\"Type a keyword and hit enter\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"sidebar-box ftco-animate fadeInUp ftco-animated\">\r\n");
      out.write("              <div class=\"categories\">\r\n");
      out.write("                <h3 class=\"heading-3\">Jobs</h3>\r\n");
      out.write("                <li><a href=\"#\">Graphic Designer <span>(12)</span></a></li>\r\n");
      out.write("                <li><a href=\"#\">Visual Assistant <span>(22)</span></a></li>\r\n");
      out.write("                <li><a href=\"#\">Programing <span>(37)</span></a></li>\r\n");
      out.write("                <li><a href=\"#\">Office Admin <span>(42)</span></a></li>\r\n");
      out.write("                <li><a href=\"#\">Web Designer <span>(14)</span></a></li>\r\n");
      out.write("                <li><a href=\"#\">Language <span>(140)</span></a></li>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"sidebar-box ftco-animate\">\r\n");
      out.write("              <h3 class=\"heading-3\">Recent Blog</h3>\r\n");
      out.write("              <div class=\"block-21 mb-4 d-flex\">\r\n");
      out.write("                <a class=\"blog-img mr-4\" style=\"background-image: url(images/image_1.jpg);\"></a>\r\n");
      out.write("                <div class=\"text\">\r\n");
      out.write("                  <h3 class=\"heading\"><a href=\"#\">Even the all-powerful Pointing has no control about the blind texts</a></h3>\r\n");
      out.write("                  <div class=\"meta\">\r\n");
      out.write("                    <div><a href=\"#\"><span class=\"icon-calendar\"></span> July 12, 2018</a></div>\r\n");
      out.write("                    <div><a href=\"#\"><span class=\"icon-person\"></span> Admin</a></div>\r\n");
      out.write("                    <div><a href=\"#\"><span class=\"icon-chat\"></span> 19</a></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"block-21 mb-4 d-flex\">\r\n");
      out.write("                <a class=\"blog-img mr-4\" style=\"background-image: url(images/image_2.jpg);\"></a>\r\n");
      out.write("                <div class=\"text\">\r\n");
      out.write("                  <h3 class=\"heading\"><a href=\"#\">Even the all-powerful Pointing has no control about the blind texts</a></h3>\r\n");
      out.write("                  <div class=\"meta\">\r\n");
      out.write("                    <div><a href=\"#\"><span class=\"icon-calendar\"></span> July 12, 2018</a></div>\r\n");
      out.write("                    <div><a href=\"#\"><span class=\"icon-person\"></span> Admin</a></div>\r\n");
      out.write("                    <div><a href=\"#\"><span class=\"icon-chat\"></span> 19</a></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"block-21 mb-4 d-flex\">\r\n");
      out.write("                <a class=\"blog-img mr-4\" style=\"background-image: url(images/image_3.jpg);\"></a>\r\n");
      out.write("                <div class=\"text\">\r\n");
      out.write("                  <h3 class=\"heading\"><a href=\"#\">Even the all-powerful Pointing has no control about the blind texts</a></h3>\r\n");
      out.write("                  <div class=\"meta\">\r\n");
      out.write("                    <div><a href=\"#\"><span class=\"icon-calendar\"></span> July 12, 2018</a></div>\r\n");
      out.write("                    <div><a href=\"#\"><span class=\"icon-person\"></span> Admin</a></div>\r\n");
      out.write("                    <div><a href=\"#\"><span class=\"icon-chat\"></span> 19</a></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"sidebar-box ftco-animate\">\r\n");
      out.write("              <h3 class=\"heading-3\">Tag Cloud</h3>\r\n");
      out.write("              <div class=\"tagcloud\">\r\n");
      out.write("                <a href=\"#\" class=\"tag-cloud-link\">dish</a>\r\n");
      out.write("                <a href=\"#\" class=\"tag-cloud-link\">menu</a>\r\n");
      out.write("                <a href=\"#\" class=\"tag-cloud-link\">food</a>\r\n");
      out.write("                <a href=\"#\" class=\"tag-cloud-link\">sweet</a>\r\n");
      out.write("                <a href=\"#\" class=\"tag-cloud-link\">tasty</a>\r\n");
      out.write("                <a href=\"#\" class=\"tag-cloud-link\">delicious</a>\r\n");
      out.write("                <a href=\"#\" class=\"tag-cloud-link\">desserts</a>\r\n");
      out.write("                <a href=\"#\" class=\"tag-cloud-link\">drinks</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"sidebar-box ftco-animate\">\r\n");
      out.write("              <h3 class=\"heading-3\">Paragraph</h3>\r\n");
      out.write("              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section> <!-- .section -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<section class=\"ftco-section-parallax\">\r\n");
      out.write("      <div class=\"parallax-img d-flex align-items-center\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("            <div class=\"col-md-7 text-center heading-section heading-section-white ftco-animate\">\r\n");
      out.write("              <h2>Subcribe to our Newsletter</h2>\r\n");
      out.write("              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in</p>\r\n");
      out.write("              <div class=\"row d-flex justify-content-center mt-4 mb-4\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                  <form action=\"#\" class=\"subscribe-form\">\r\n");
      out.write("                    <div class=\"form-group d-flex\">\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\" placeholder=\"Enter email address\">\r\n");
      out.write("                      <input type=\"submit\" value=\"Subscribe\" class=\"submit px-3\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"ftco-footer ftco-bg-dark ftco-section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row mb-5\">\r\n");
      out.write("        \t<div class=\"col-md\">\r\n");
      out.write("             <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("              <h2 class=\"ftco-heading-2\">Skillhunt Jobboard</h2>\r\n");
      out.write("              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("              <ul class=\"ftco-footer-social list-unstyled float-md-left float-lft mt-3\">\r\n");
      out.write("                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-twitter\"></span></a></li>\r\n");
      out.write("                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-facebook\"></span></a></li>\r\n");
      out.write("                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-instagram\"></span></a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md\">\r\n");
      out.write("            <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("              <h2 class=\"ftco-heading-2\">Employers</h2>\r\n");
      out.write("              <ul class=\"list-unstyled\">\r\n");
      out.write("                <li><a href=\"#\" class=\"pb-1 d-block\">Browse Candidates</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"pb-1 d-block\">Post a Job</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"pb-1 d-block\">Employer Listing</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"pb-1 d-block\">Resume Page</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"pb-1 d-block\">Dashboard</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"pb-1 d-block\">Job Packages</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md\">\r\n");
      out.write("            <div class=\"ftco-footer-widget mb-4 ml-md-4\">\r\n");
      out.write("              <h2 class=\"ftco-heading-2\">Candidate</h2>\r\n");
      out.write("              <ul class=\"list-unstyled\">\r\n");
      out.write("                <li><a href=\"#\" class=\"pb-1 d-block\">Browse Jobs</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"pb-1 d-block\">Submit Resume</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"pb-1 d-block\">Dashboard</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"pb-1 d-block\">Browse Categories</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"pb-1 d-block\">My Bookmarks</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"pb-1 d-block\">Candidate Listing</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md\">\r\n");
      out.write("            <div class=\"ftco-footer-widget mb-4 ml-md-4\">\r\n");
      out.write("              <h2 class=\"ftco-heading-2\">Account</h2>\r\n");
      out.write("              <ul class=\"list-unstyled\">\r\n");
      out.write("                <li><a href=\"#\" class=\"pb-1 d-block\">My Account</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"pb-1 d-block\">Sign In</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"pb-1 d-block\">Create Account</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"pb-1 d-block\">Checkout</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md\">\r\n");
      out.write("            <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("            \t<h2 class=\"ftco-heading-2\">Have a Questions?</h2>\r\n");
      out.write("            \t<div class=\"block-23 mb-3\">\r\n");
      out.write("\t              <ul>\r\n");
      out.write("\t                <li><span class=\"icon icon-map-marker\"></span><span class=\"text\">203 Fake St. Mountain View, San Francisco, California, USA</span></li>\r\n");
      out.write("\t                <li><a href=\"#\"><span class=\"icon icon-phone\"></span><span class=\"text\">+2 392 3929 210</span></a></li>\r\n");
      out.write("\t                <li><a href=\"#\"><span class=\"icon icon-envelope\"></span><span class=\"text\">info@yourdomain.com</span></a></li>\r\n");
      out.write("\t              </ul>\r\n");
      out.write("\t            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("  Copyright ©<script>document.write(new Date().getFullYear());</script>2020 All rights reserved | This template is made with <i class=\"icon-heart text-danger\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <!-- loader -->\r\n");
      out.write("  <div id=\"ftco-loader\" class=\"fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"></circle><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"></circle></svg></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script src=\"resources/js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/aos.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/scrollax.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;sensor=false\"></script>\r\n");
      out.write("  <script src=\"resources/js/google-map.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
